apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ttrpg-discord-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/m-gora/ttrpg-discord-app.git
    targetRevision: main
    path: k8s
    directory:
      recurse: false

  destination:
    server: https://kubernetes.default.svc
    namespace: ttrpg

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
