apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ttrpg-discord-app-data
  namespace: ttrpg
  labels:
    app.kubernetes.io/name: ttrpg-discord-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Mi
